# Generated by Django 3.1.3 on 2020-12-12 15:24

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sensitive_data',
            field=models.OneToOneField(default=myapp.models._get_default_sensitive_data, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.sensitivedata', verbose_name='Sensitive Data'),
        ),
    ]
